#include "emu.h"

char *disassemble_instr(uint16_t addr) {
	static char s[100];
	uint8_t     b;
	uint16_t    w;

	if ((((uint32_t)addr)+2) <= 0xFFFF) {
		b = readByte(addr+1);
		w = readWord(addr+1);
	}
	switch (readByte(addr)) {
		case 0x00: sprintf(s, "NOP"); return s;
		case 0x01: sprintf(s, "LD BC,%04X", w); return s;
		case 0x02: sprintf(s, "LD (BC),A"); return s;
		case 0x03: sprintf(s, "INC BC"); return s;
		case 0x04: sprintf(s, "INC B"); return s;
		case 0x05: sprintf(s, "DEC B"); return s;
		case 0x06: sprintf(s, "LD B,%02X", b); return s;
		case 0x07: sprintf(s, "RLCA"); return s;
		case 0x08: sprintf(s, "LD (%04X),SP", w); return s;
		case 0x09: sprintf(s, "ADD HL,BC"); return s;
		case 0x0A: sprintf(s, "LD A,(BC)"); return s;
		case 0x0B: sprintf(s, "DEC BC"); return s;
		case 0x0C: sprintf(s, "INC C"); return s;
		case 0x0D: sprintf(s, "DEC C"); return s;
		case 0x0E: sprintf(s, "LD C,%02X", b); return s;
		case 0x0F: sprintf(s, "RRCA"); return s;
		case 0x10: sprintf(s, "STOP 0"); return s;
		case 0x11: sprintf(s, "LD DE,%04X", w); return s;
		case 0x12: sprintf(s, "LD (DE),A"); return s;
		case 0x13: sprintf(s, "INC DE"); return s;
		case 0x14: sprintf(s, "INC D"); return s;
		case 0x15: sprintf(s, "DEC D"); return s;
		case 0x16: sprintf(s, "LD D,%02X", b); return s;
		case 0x17: sprintf(s, "RLA"); return s;
		case 0x18: sprintf(s, "JR %02X", b); return s;
		case 0x19: sprintf(s, "ADD HL,DE"); return s;
		case 0x1A: sprintf(s, "LD A,(DE)"); return s;
		case 0x1B: sprintf(s, "DEC DE"); return s;
		case 0x1C: sprintf(s, "INC E"); return s;
		case 0x1D: sprintf(s, "DEC E"); return s;
		case 0x1E: sprintf(s, "LD E,%02X", b); return s;
		case 0x1F: sprintf(s, "RRA"); return s;
		case 0x20: sprintf(s, "JR NZ,%02X", b); return s;
		case 0x21: sprintf(s, "LD HL,%04X", w); return s;
		case 0x22: sprintf(s, "LD (HL+),A"); return s;
		case 0x23: sprintf(s, "INC HL"); return s;
		case 0x24: sprintf(s, "INC H"); return s;
		case 0x25: sprintf(s, "DEC H"); return s;
		case 0x26: sprintf(s, "LD H,%02X", b); return s;
		case 0x27: sprintf(s, "DAA"); return s;
		case 0x28: sprintf(s, "JR Z,%02X", b); return s;
		case 0x29: sprintf(s, "ADD HL,HL"); return s;
		case 0x2A: sprintf(s, "LD A,(HL+)"); return s;
		case 0x2B: sprintf(s, "DEC HL"); return s;
		case 0x2C: sprintf(s, "INC L"); return s;
		case 0x2D: sprintf(s, "DEC L"); return s;
		case 0x2E: sprintf(s, "LD L,%02X", b); return s;
		case 0x2F: sprintf(s, "CPL"); return s;
		case 0x30: sprintf(s, "JR NC,%02X", b); return s;
		case 0x31: sprintf(s, "LD SP,%04X", w); return s;
		case 0x32: sprintf(s, "LD (HL-),A"); return s;
		case 0x33: sprintf(s, "INC SP"); return s;
		case 0x34: sprintf(s, "INC (HL)"); return s;
		case 0x35: sprintf(s, "DEC (HL)"); return s;
		case 0x36: sprintf(s, "LD (HL),%02X", b); return s;
		case 0x37: sprintf(s, "SCF"); return s;
		case 0x38: sprintf(s, "JR C,%02X", b); return s;
		case 0x39: sprintf(s, "ADD HL,SP"); return s;
		case 0x3A: sprintf(s, "LD A,(HL-)"); return s;
		case 0x3B: sprintf(s, "DEC SP"); return s;
		case 0x3C: sprintf(s, "INC A"); return s;
		case 0x3D: sprintf(s, "DEC A"); return s;
		case 0x3E: sprintf(s, "LD A,%02X", b); return s;
		case 0x3F: sprintf(s, "CCF"); return s;
		case 0x40: sprintf(s, "LD B,B"); return s;
		case 0x41: sprintf(s, "LD B,C"); return s;
		case 0x42: sprintf(s, "LD B,D"); return s;
		case 0x43: sprintf(s, "LD B,E"); return s;
		case 0x44: sprintf(s, "LD B,H"); return s;
		case 0x45: sprintf(s, "LD B,L"); return s;
		case 0x46: sprintf(s, "LD B,(HL)"); return s;
		case 0x47: sprintf(s, "LD B,A"); return s;
		case 0x48: sprintf(s, "LD C,B"); return s;
		case 0x49: sprintf(s, "LC C,C"); return s;
		case 0x4A: sprintf(s, "LD C,D"); return s;
		case 0x4B: sprintf(s, "LD C,E"); return s;
		case 0x4C: sprintf(s, "LD C,H"); return s;
		case 0x4D: sprintf(s, "LD C,L"); return s;
		case 0x4E: sprintf(s, "LD C,(HL)"); return s;
		case 0x4F: sprintf(s, "LD C,A"); return s;
		case 0x50: sprintf(s, "LD D,B"); return s;
		case 0x51: sprintf(s, "LD D,C"); return s;
		case 0x52: sprintf(s, "LD D,B"); return s;
		case 0x53: sprintf(s, "LD D,E"); return s;
		case 0x54: sprintf(s, "LD D,H"); return s;
		case 0x55: sprintf(s, "LD D,L"); return s;
		case 0x56: sprintf(s, "LD D,(HL)"); return s;
		case 0x57: sprintf(s, "LD D,A"); return s;
		case 0x58: sprintf(s, "LD E,B"); return s;
		case 0x59: sprintf(s, "LD E,C"); return s;
		case 0x5A: sprintf(s, "LD E,D"); return s;
		case 0x5B: sprintf(s, "LD E,E"); return s;
		case 0x5C: sprintf(s, "LD E,H"); return s;
		case 0x5D: sprintf(s, "LD E,L"); return s;
		case 0x5E: sprintf(s, "LD E,(HL)"); return s;
		case 0x5F: sprintf(s, "LD E,A"); return s;
		case 0x60: sprintf(s, "LD H,B"); return s;
		case 0x61: sprintf(s, "LD H,C"); return s;
		case 0x62: sprintf(s, "LD H,D"); return s;
		case 0x63: sprintf(s, "LD H,E"); return s;
		case 0x64: sprintf(s, "LD H,H"); return s;
		case 0x65: sprintf(s, "LD H,L"); return s;
		case 0x66: sprintf(s, "LD H,(HL)"); return s;
		case 0x67: sprintf(s, "LD H,A"); return s;
		case 0x68: sprintf(s, "LD L,B"); return s;
		case 0x69: sprintf(s, "LD L,C"); return s;
		case 0x6A: sprintf(s, "LD L,D"); return s;
		case 0x6B: sprintf(s, "LD L,E"); return s;
		case 0x6C: sprintf(s, "LD L,H"); return s;
		case 0x6D: sprintf(s, "LD L,L"); return s;
		case 0x6E: sprintf(s, "LD L,(HL)"); return s;
		case 0x6F: sprintf(s, "LD L,A"); return s;
		case 0x70: sprintf(s, "LD (HL),B"); return s;
		case 0x71: sprintf(s, "LD (HL),C"); return s;
		case 0x72: sprintf(s, "LD (HL),D"); return s;
		case 0x73: sprintf(s, "LD (HL),E"); return s;
		case 0x74: sprintf(s, "LD (HL),H"); return s;
		case 0x75: sprintf(s, "LD (HL),L"); return s;
		case 0x76: sprintf(s, "HALT"); return s;
		case 0x77: sprintf(s, "LD (HL),A"); return s;
		case 0x78: sprintf(s, "LD A,B"); return s;
		case 0x79: sprintf(s, "LD A,C"); return s;
		case 0x7A: sprintf(s, "LD A,D"); return s;
		case 0x7B: sprintf(s, "LD A,E"); return s;
		case 0x7C: sprintf(s, "LD A,H"); return s;
		case 0x7D: sprintf(s, "LD A,L"); return s;
		case 0x7E: sprintf(s, "LD A,(HL)"); return s;
		case 0x7F: sprintf(s, "LD A,A"); return s;
		case 0x80: sprintf(s, "ADD A,B"); return s;
		case 0x81: sprintf(s, "ADD A,C"); return s;
		case 0x82: sprintf(s, "ADD A,D"); return s;
		case 0x83: sprintf(s, "ADD A,E"); return s;
		case 0x84: sprintf(s, "ADD A,H"); return s;
		case 0x85: sprintf(s, "ADD A,L"); return s;
		case 0x86: sprintf(s, "ADD A,(HL)"); return s;
		case 0x87: sprintf(s, "ADD A,A"); return s;
		case 0x88: sprintf(s, "ADC A,B"); return s;
		case 0x89: sprintf(s, "ADC A,C"); return s;
		case 0x8A: sprintf(s, "ADC A,D"); return s;
		case 0x8B: sprintf(s, "ADC A,E"); return s;
		case 0x8C: sprintf(s, "ADC A,H"); return s;
		case 0x8D: sprintf(s, "ADC A,L"); return s;
		case 0x8E: sprintf(s, "ADC A,(HL)"); return s;
		case 0x8F: sprintf(s, "ADC A,A"); return s;
		case 0x90: sprintf(s, "SUB B"); return s;
		case 0x91: sprintf(s, "SUB C"); return s;
		case 0x92: sprintf(s, "SUB D"); return s;
		case 0x93: sprintf(s, "SUB E"); return s;
		case 0x94: sprintf(s, "SUB H"); return s;
		case 0x95: sprintf(s, "SUB L"); return s;
		case 0x96: sprintf(s, "SUB (HL)"); return s;
		case 0x97: sprintf(s, "SUB A"); return s;
		case 0x98: sprintf(s, "SBC A,B"); return s;
		case 0x99: sprintf(s, "SBC A,C"); return s;
		case 0x9A: sprintf(s, "SBC A,D"); return s;
		case 0x9B: sprintf(s, "SBC A,E"); return s;
		case 0x9C: sprintf(s, "SBC A,H"); return s;
		case 0x9D: sprintf(s, "SBC A,L"); return s;
		case 0x9E: sprintf(s, "SBC A,(HL)"); return s;
		case 0x9F: sprintf(s, "SBC A,A"); return s;
		case 0xA0: sprintf(s, "AND B"); return s;
		case 0xA1: sprintf(s, "AND C"); return s;
		case 0xA2: sprintf(s, "AND D"); return s;
		case 0xA3: sprintf(s, "AND E"); return s;
		case 0xA4: sprintf(s, "AND H"); return s;
		case 0xA5: sprintf(s, "AND L"); return s;
		case 0xA6: sprintf(s, "AND (HL)"); return s;
		case 0xA7: sprintf(s, "AND A"); return s;
		case 0xA8: sprintf(s, "XOR B"); return s;
		case 0xA9: sprintf(s, "XOR C"); return s;
		case 0xAA: sprintf(s, "XOR D"); return s;
		case 0xAB: sprintf(s, "XOR E"); return s;
		case 0xAC: sprintf(s, "XOR H"); return s;
		case 0xAD: sprintf(s, "XOR L"); return s;
		case 0xAE: sprintf(s, "XOR (HL)"); return s;
		case 0xAF: sprintf(s, "XOR A"); return s;
		case 0xB0: sprintf(s, "OR B"); return s;
		case 0xB1: sprintf(s, "OR C"); return s;
		case 0xB2: sprintf(s, "OR D"); return s;
		case 0xB3: sprintf(s, "OR E"); return s;
		case 0xB4: sprintf(s, "OR H"); return s;
		case 0xB5: sprintf(s, "OR L"); return s;
		case 0xB6: sprintf(s, "OR (HL)"); return s;
		case 0xB7: sprintf(s, "OR A"); return s;
		case 0xB8: sprintf(s, "CP B"); return s;
		case 0xB9: sprintf(s, "CP C"); return s;
		case 0xBA: sprintf(s, "CP D"); return s;
		case 0xBB: sprintf(s, "CP E"); return s;
		case 0xBC: sprintf(s, "CP H"); return s;
		case 0xBD: sprintf(s, "CP L"); return s;
		case 0xBE: sprintf(s, "CP (HL)"); return s;
		case 0xBF: sprintf(s, "CP A"); return s;
		case 0xC0: sprintf(s, "RET NZ"); return s;
		case 0xC1: sprintf(s, "POP BC"); return s;
		case 0xC2: sprintf(s, "JP NZ %04X", w); return s;
		case 0xC3: sprintf(s, "JP %04X", w); return s;
		case 0xC4: sprintf(s, "CALL NZ,%04X", w); return s;
		case 0xC5: sprintf(s, "PUSH BC"); return s;
		case 0xC6: sprintf(s, "ADD A,%02X", b); return s;
		case 0xC7: sprintf(s, "RST 00H"); return s;
		case 0xC8: sprintf(s, "RET Z"); return s;
		case 0xC9: sprintf(s, "RET"); return s;
		case 0xCA: sprintf(s, "JP Z,%04X", w); return s;
		case 0xCB: sprintf(s, "PREFIX CB"); return s;
		case 0xCC: sprintf(s, "CALL Z,%04X", w); return s;
		case 0xCD: sprintf(s, "CALL %04X", w); return s;
		case 0xCE: sprintf(s, "ADC A, %02X", b); return s;
		case 0xCF: sprintf(s, "RST 08H"); return s;
		case 0xD0: sprintf(s, "RET NC"); return s;
		case 0xD1: sprintf(s, "POP DE"); return s;
		case 0xD2: sprintf(s, "JP NC,%04X", w); return s;
		case 0xD3: sprintf(s, "INVALID"); return s;
		case 0xD4: sprintf(s, "CALL NC,%04X", w); return s;
		case 0xD5: sprintf(s, "PUSH DE"); return s;
		case 0xD6: sprintf(s, "SUB %02X", b); return s;
		case 0xD7: sprintf(s, "RST 10H"); return s;
		case 0xD8: sprintf(s, "RET C"); return s;
		case 0xD9: sprintf(s, "RETI"); return s;
		case 0xDA: sprintf(s, "JP C,%04X", w); return s;
		case 0xDB: sprintf(s, "INVALID"); return s;
		case 0xDC: sprintf(s, "CALL C,%04X", w); return s;
		case 0xDD: sprintf(s, "INVALID"); return s;
		case 0xDE: sprintf(s, "SBC A,%02X", b); return s;
		case 0xDF: sprintf(s, "RST 18H"); return s;
		case 0xE0: sprintf(s, "LDH (%02X),A", b); return s;
		case 0xE1: sprintf(s, "POP HL"); return s;
		case 0xE2: sprintf(s, "LD (C),A"); return s;
		case 0xE3: sprintf(s, "INVALID"); return s;
		case 0xE4: sprintf(s, "INVALID"); return s;
		case 0xE5: sprintf(s, "PUSH HL"); return s;
		case 0xE6: sprintf(s, "AND %02X", b); return s;
		case 0xE7: sprintf(s, "RST 20H"); return s;
		case 0xE8: sprintf(s, "ADD SP,%02X", b); return s;
		case 0xE9: sprintf(s, "JP (HL)"); return s;
		case 0xEA: sprintf(s, "LD (%04X),A", w); return s;
		case 0xEB: sprintf(s, "INVALID"); return s;
		case 0xEC: sprintf(s, "INVALID"); return s;
		case 0xED: sprintf(s, "INVALID"); return s;
		case 0xEE: sprintf(s, "XOR %02X", b); return s;
		case 0xEF: sprintf(s, "RST 28H"); return s;
		case 0xF0: sprintf(s, "LDH A,(%02X)", b); return s;
		case 0xF1: sprintf(s, "POP AF"); return s;
		case 0xF2: sprintf(s, "LD A,(C)"); return s;
		case 0xF3: sprintf(s, "DI"); return s;
		case 0xF4: sprintf(s, "INVALID"); return s;
		case 0xF5: sprintf(s, "PUSH AF"); return s;
		case 0xF6: sprintf(s, "OR %02X", b); return s;
		case 0xF7: sprintf(s, "RST 30H"); return s;
		case 0xF8: sprintf(s, "LD HL,SP+%02X", b); return s;
		case 0xF9: sprintf(s, "LD SP,HL"); return s;
		case 0xFA: sprintf(s, "LD A,(%04X)", w); return s;
		case 0xFB: sprintf(s, "EI"); return s;
		case 0xFC: sprintf(s, "INVALID"); return s;
		case 0xFD: sprintf(s, "INVALID"); return s;
		case 0xFE: sprintf(s, "CP %02X", b); return s;
		case 0xFF: sprintf(s, "RST 38H"); return s;
	}
}